### ISSUE TITLE
How to define submission.py and my_controller

### ISSUE THREAD

**Issue by ChaoYue97** [jidiai/GRF_MARL#4]
I want to submit my model on Jidiai.cn, but how can I upload the. pt file I trained effectively? Is there an example tutorial available?

**Comment by YanSong97** [comment]
Yes, this competition [repo](https://github.com/jidiai/Competition_COG2023) is the tutorial for the football competition in the previous year. You can put your submission in `/agent` file (see [link](https://github.com/jidiai/Competition_COG2023/tree/main/agents)) and test it by running `run_log.py`.

**Comment by qq591822071** [comment]
Compared to the demo of the random submission file and the dpn algorithm of carpole, I still cannot write the submission file for the PSRO algorithm. So now I want to know if there is a local simulation method for comparing the performance of models in the GRF-MARL environment. Currently, what I have trained is actor. py The three files are critic.pt and desc.pkl. Because I want to test whether my improvements to the algorithm are effective, and I want to get methods for online or local battles.
